 export const samplefoods=[
    {
      id: '1',
      name: 'Biriyani',
      cookTime: '10-20',
      price: 160,
      favorite: false,
      origins: ['south indian ', 'North indian'],
      stars: 4.5,
      imageUrl: 'food1.jpg',
      tags: ['Meals', 'Lunch','SlowFood'],
    },
    {
      id: '2',
      name: 'Meals',
      price: 100,
      cookTime: '20-30',
      favorite: true,
      origins: ['madurai', 'salem', 'chennai'],
      stars: 5,
      imageUrl: 'food2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 70,
      cookTime: '10-15',
      favorite: false,
      origins: ['US', 'UK'],
      stars: 3.5,
      imageUrl: 'food3.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id: '4',
      name: 'Dosai',
      price: 30,
      cookTime: '15-20',
      favorite: true,
      origins: ['south indian','North indian'],
      stars: 3,
      imageUrl: 'food4.jpg',
      tags: ['FastFood', 'Tiffin'],
    },
    {
      id: '5',
      name: 'Chicken rise',
      price: 120,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia','Thai'],
      stars: 3.5,
      imageUrl: 'food5.jpg',
      tags: ['FastFood', 'Fry'],
    },
    {
      id: '6',
      name: 'Parota',
      price: 20,
      cookTime: '40-50',
      favorite: false,
      origins: ['Madurai','Chennai'],
      stars: 4.0,
      imageUrl: 'food6.jpg',
      tags: ['FastFood', 'Meals', 'Lunch'],
    },
    {
      id: '7',
      name: 'Pongal',
      price: 20,
      cookTime: '40-50',
      favorite: false,
      origins: ['south indian'],
      stars: 4.0,
      imageUrl: 'food7.jpg',
      tags: ['Tiffin', 'SlowFood'],
    },
    {
      id: '8',
      name: 'Poori',
      price: 20,
      cookTime: '40-50',
      favorite: true,
      origins: ['south indian'],
      stars: 4.0,
      imageUrl: 'food8.jpg',
      tags: ['FastFood', 'Tiffin'],
    },
    {
      id: '9',
      name: 'Idly',
      price: 10,
      cookTime: '40-50',
      favorite: false,
      origins: ['south indian'],
      stars: 4.0,
      imageUrl: 'food9.jpg',
      tags: ['Tiffin'],
    },
    {
      id: '10',
      name: 'coffee',
      price: 80,
      cookTime: '40-50',
      favorite: true,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'food10.jpg',
      tags: [ 'drink'],
    },
  ];
  
  export const sampletags = [
    { name: 'All', count: 9 },
    { name: 'FastFood', count: 5 },
    { name: 'Tiffin', count: 4 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 3 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'drink', count: 1 },
  ];
  
//   export const sample_users = [
//     {
//       id: 1,
//       name: 'John Doe',
//       email: 'john@gmail.com',
//       password: '12345',
//       address: 'Toronto On',
//       isAdmin: false,
//     },
//     {
//       id: 2,
//       name: 'Jane Doe',
//       email: 'jane@gmail.com',
//       password: '12345',
//       address: 'Shanghai',
//       isAdmin: true,
//     },
 // ];
  